Repository ibonksoftserve/toxic-project-gen1, pull requests merged in 2022-04, with the labels that each got.

#1 ib/ init frontend
  README.md
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/react-app-env.d.ts
  frontend/src/reportWebVitals.ts
  frontend/src/setupTests.ts
  frontend/tsconfig.json
  package.json
Labels: architecture

#7 Setup linter for React app
  .tool-versions
  frontend/.eslintignore
  frontend/.eslintrc.json
  frontend/.stylelintrc.json
  frontend/.vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/tsconfig.json
Labels: architecture, FE

#8 Husky setup
  .husky/post-commit
  .husky/pre-commit
  frontend/.eslintignore
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.css
  frontend/src/index.tsx
Labels: question, architecture, FE

#14 ib/ add validation and errors handling
  backend/app/core/api.errors.ts
  backend/app/core/api.interface.ts
  backend/app/core/api.response.ts
  backend/app/loaders/express.ts
  backend/app/middlewares/async-handler.ts
  backend/app/middlewares/errors-handler.ts
  backend/app/middlewares/request-logger.ts
  backend/app/middlewares/validator.ts
  backend/app/modules/user/user.controller.ts
  backend/app/modules/user/user.factory.ts
  backend/app/modules/user/user.routes.ts
  backend/app/modules/user/user.schema.ts
  backend/app/shared/validators.ts
  backend/package-lock.json
  backend/package.json
  package.json
Labels: architecture, BE
